app:
  appId:
  appSecret:
  loginUrl: https://api.nftrainbow.xyz/v1/login
bot:
  token:
easyMint:
  chain: conflux_test
  url: https://api.nftrainbow.xyz/v1/mints/easy/urls
  fileUrl:
  name:
  description:
  mintRespPrefix: https://testnet.confluxscan.io/nft/cfxtest:acgraybn1g1upesed09g96vxev79sdhmxjmz7bxzyy/
  infoUrl: https://api.nftrainbow.xyz/v1/mints/


