app:
  app_id:
  app_secret:
  login_url: https://api.nftrainbow.xyz/v1/login
bot:
  token:
easymint:
  chain: conflux_test
  url: https://api.nftrainbow.xyz/v1/mints/easy/urls
  file_url:
  name:
  description:
  mintRespPrefix: https://testnet.confluxscan.io/nft/cfxtest:acgraybn1g1upesed09g96vxev79sdhmxjmz7bxzyy/
getInfo_url: https://api.nftrainbow.xyz/v1/mints/


