host: https://api.nftrainbow.xyz/
app:
  appId:
  appSecret:
botToken:
chainType: conflux_test
easyMint:
  fileUrl:
  name:
  description:
mintRespPrefix: https://testnet.confluxscan.io/nft/
customMint:
  fileUrl:
  name:
  description:
  contractType:
  contractAddress:


