app:
  appId:
  appSecret:
  loginUrl: https://api.nftrainbow.xyz/v1/login
bot:
  token:
fileUploadUrl: https://api.nftrainbow.xyz/v1/files
deployContract:
  type: erc721
  name:
  deployUrl:
  infoUrl:
advertise: Powered by NFTRainbow


